  name: 'Run Parasoft SOAtest'
  description: 'A GitHub Action for running functional tests with Parasoft SOAtest and reviewing results directly in GitHub.'
  author: 'Parasoft'
  branding:
    icon: 'aperture'
    color: 'blue'
  inputs:
    installDir: C:/Program Files/Parasoft/SOAtest_Virtualize/2022.1
    workingDir: D:/soa-workspace
    testConfig: builtin://Demo Configuration
    resource: TestAssets
    settings: localsettings.properties
    report: report-parabank-soatest-action
    reportFormat: xml
      default: 'xml,html'
    environment: 
      description: 'Name of the SOAtest environment to use for executing the tests.'
      required: false
    convertReportToXUnit: false
      description: 'Enables the conversion of the SOAtest report into the xUnit format.'
      required: false
      default: true
    javaRootPath: C:/Program Files/Java/jdk-11/bin
      description: 'Absolute location of the root path of Java installation. When found at the specified location, Java optimizes the efficiency of report processing. Otherwise, report processing will be significantly slower and may encounter memory issues when handling large reports.'
      required: false
    additionalParams:
      description: 'Additional parameters for the soatestcli executable.'
      required: false
  runs:
    using: node20
    main: 'dist/index.js'
